### ISSUE TITLE
common issue during the lab, unlimited key is generated but not activated, so it always fails for new beginners

### ISSUE THREAD

**Issue by feranto** [feranto/azure-apim-lab#11]

**Comment by markharrison** [comment]
It gives the opportunity to show / discuss the Products Policy where you can specify if a subscription is automatically approved or have to be admin approved.  The script should clarify that the admin has to approve Unlimited subscriptions - but not Starter subscriptions.

**Comment by ferantoMSFT** [comment]
closed as it is part of the approval process of the admin portal and the products configuration
